### PR TITLE
[DO NOT MERGE] nac_docker_support.sh: spelling in log message

### PR DESCRIPTION
**Pull request by trapier**
/cc @vidurous.

:-P

### CODE REVIEW

**Comment by trapier** [comment]
do not merge.  my first time editing via github web ui.  would be evil to leave a github username in commit.  mentions in perpetuity.

editing commit message.

**Comment by trapier** [comment]
well that's dumb.  i can't find `patch-1` in my fork.  closing this.

**Review by vidurous — COMMENTED** [review]
works for me

**Comment by vidurous** [comment]
@trapier

Just seeing this :/

> do not merge. my first time editing via github web ui. would be evil to leave a github username in commit. mentions in perpetuity.

**Pull request merged**
